spring.application.name=demo
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/diplom
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JDBC настройки
spring.datasource.initialization-mode=always

# LOGER
spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
logging.level.APP=DEBUG

python.service.url=http://task-runner:8000


# Максимальный размер одного файла
spring.servlet.multipart.max-file-size=50MB
# Максимальный размер всего запроса
spring.servlet.multipart.max-request-size=50MB